[project]
name = "jp-housing-pred"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Towen Chan", email = "towen.chan@gmail.com" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
jp-housing-pred = "jp_housing_pred:main"

[build-system]
requires = ["uv_build>=0.12.1,<0.13.0"]
build-backend = "uv_build"
